# Alembic Configuration File

[alembic]
# path to migration scripts
sqlalchemy.url =
script_location = alembic

# Template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current working directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.datetime.now(timezone.utc)
# leave blank for localtime
# causes porting files from one db to another to build the same
# migration name, even when it has different migrating structure
# when datetime.datetime.now(timezone.utc) is used, it is only
# used as default value and real value is resolved by the
# UpgradeOps.execution_options with sqlalchemy 1.4 or greater.
# string value is passed to datetime.datetime.now(timezone.utc)
sqlalchemy.echo = false

# max length of characters to apply to the
# "slug" field in the migration name template
# Can also be passed as --sql-help with alembic init
sqlalchemy.max_identifier_length = 63

# migration identifiers, as configured
# version_location_template = %(here)s/db_migrations/%%(branch_label)s/%%(version_num)s_%%(slug)s

# set multiple databases for the "multi" -c option
# Configure the sqlalchemy.url setting in either .env file or environment variables
# sqlalchemy.url is not needed here if SQLALCHEMY_URL env var is set

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
